### Register user
POST http://localhost:3000/api/user/register
Content-Type: application/json

{
    "email": "john@gmail.com",
    "password": "password",
    "username": "jon"
}

### Login user
POST http://localhost:3000/api/user/login
Content-Type: application/json

{
    "email": "david@gmail.com",
    "password": "david123!"
}

### Access Token reproduced
POST  http://localhost:3000/api/user/token

### Logout user
DELETE http://localhost:3000/api/user/logout

### Create Recipe 
POST http://localhost:3000/api/recipes
Content-Type: application/json

{
    "title" : "john food 2", 
    "duration": "45min", 
    "category": "Breakfast", 
    "area": "Asian", 
    "videolink": "youtube.com",
    "ingredients": [
        {
            "name": "ingredient1",
            "quantity": "1tbsp"
        },
        {
            "name": "ingredient2",
            "quantity": "1tbsp"
        }
    ],
    "instructions": [
        "instruction1","instruction2","instrcution3"
    ]
}

### Select All recipes
GET http://localhost:3000/api/recipes

### Select All recipes by user
GET http://localhost:3000/api/recipes/private

### select recipe by id
GET http://localhost:3000/api/recipes/646f1d8031c09da918247743


### get recipes by search
GET http://localhost:3000/api/recipes/search/gbrgbfg

### get recipes by search
GET http://localhost:3000/api/recipes/search/drink

### get recipes by search
GET http://localhost:3000/api/recipes/search/chinese
### Edit recipe by id for user
PUT http://localhost:3000/api/recipes/edit/646f1e0b31c09da91824774a
Content-Type: application/json

{

}

### Delete recipe by id for user
DELETE http://localhost:3000/api/recipes/delete/6460f5c4ddc006fbf5278e28

### Get all liked recipe 
GET http://localhost:3000/api/liked

### Add like recipe to the user
PUT http://localhost:3000/api/liked/6460f599ddc006fbf5278e15

### Delete like recipe from the user
DELETE http://localhost:3000/api/liked/6460f599ddc006fbf5278e15

### Auth access
POST  http://localhost:3000/api/user/auth